# Site settings
title: Concrete Mathematics
description: "一个由Dengqi组织的对具体数学的开源翻译"
url: "http://blog.dengqi.org/Concrete-mathematics"
author:
  name: "Dengqi"
  url: "http://blog.dengqi.org"

# Build settings
baseurl: / # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Custom variables
version: "1.0.1"
